dtypes:
  MachineIdentifier: 'category'
  ProductName: 'category'
  EngineVersion: 'category'
  AppVersion: 'category'
  AvSigVersion: 'category'
  IsBeta: 'int8'
  RtpStateBitfield: 'float32'
  IsSxsPassiveMode: 'int8'
  DefaultBrowsersIdentifier: 'float32'
  AVProductStatesIdentifier: 'float32'
  AVProductsInstalled: 'float32'
  AVProductsEnabled: 'float32'
  HasTpm: 'int8'
  CountryIdentifier: 'int16'
  CityIdentifier: 'float32'
  OrganizationIdentifier: 'float32'
  GeoNameIdentifier: 'float32'
  LocaleEnglishNameIdentifier: 'int8'
  Platform: 'category'
  Processor: 'category'
  OsVer: 'category'
  OsBuild: 'int16'
  OsSuite: 'int16'
  OsPlatformSubRelease: 'category'
  OsBuildLab: 'category'
  SkuEdition: 'category'
  IsProtected: 'float32'
  AutoSampleOptIn: 'int8'
  PuaMode: 'category'
  SMode: 'float32'
  IeVerIdentifier: 'float32'
  SmartScreen: 'category'
  Firewall: 'float32'
  UacLuaenable: 'float32'
  Census_MDC2FormFactor: 'category'
  Census_DeviceFamily: 'category'
  Census_OEMNameIdentifier: 'float32'
  Census_OEMModelIdentifier: 'float32'
  Census_ProcessorCoreCount: 'float32'
  Census_ProcessorManufacturerIdentifier: 'float32'
  Census_ProcessorModelIdentifier: 'float32'
  Census_ProcessorClass: 'category'
  Census_PrimaryDiskTotalCapacity: 'float32'
  Census_PrimaryDiskTypeName: 'category'
  Census_SystemVolumeTotalCapacity: 'float32'
  Census_HasOpticalDiskDrive: 'int8'
  Census_TotalPhysicalRAM: 'float32'
  Census_ChassisTypeName: 'category'
  Census_InternalPrimaryDiagonalDisplaySizeInInches: 'float32'
  Census_InternalPrimaryDisplayResolutionHorizontal: 'float32'
  Census_InternalPrimaryDisplayResolutionVertical: 'float32'
  Census_PowerPlatformRoleName: 'category'
  Census_InternalBatteryType: 'category'
  Census_InternalBatteryNumberOfCharges: 'float32'
  Census_OSVersion: 'category'
  Census_OSArchitecture: 'category'
  Census_OSBranch: 'category'
  Census_OSBuildNumber: 'int16'
  Census_OSBuildRevision: 'int32'
  Census_OSEdition: 'category'
  Census_OSSkuName: 'category'
  Census_OSInstallTypeName: 'category'
  Census_OSInstallLanguageIdentifier: 'float32'
  Census_OSUILocaleIdentifier: 'int16'
  Census_OSWUAutoUpdateOptionsName: 'category'
  Census_IsPortableOperatingSystem: 'int8'
  Census_GenuineStateName: 'category'
  Census_ActivationChannel: 'category'
  Census_IsFlightingInternal: 'float32'
  Census_IsFlightsDisabled: 'float32'
  Census_FlightRing: 'category'
  Census_ThresholdOptIn: 'float32'
  Census_FirmwareManufacturerIdentifier: 'float32'
  Census_FirmwareVersionIdentifier: 'float32'
  Census_IsSecureBootEnabled: 'int8'
  Census_IsWIMBootEnabled: 'float32'
  Census_IsVirtualDevice: 'float32'
  Census_IsTouchEnabled: 'int8'
  Census_IsPenCapable: 'int8'
  Census_IsAlwaysOnAlwaysConnectedCapable: 'float32'
  Wdft_IsGamer: 'float32'
  Wdft_RegionIdentifier: 'float32'
  HasDetections: 'int8'
