features:
  MachineIdentifier:
    description: "Individual machine ID"
    data_type: "category"
    importance: "high"
  ProductName:
    description: "Defender state information e.g. win8defender"
    data_type: "category"
    importance: "medium"
  EngineVersion:
    description: "Defender state information e.g. 1.1.12603.0"
    data_type: "category"
    importance: "medium"
  AppVersion:
    description: "Defender state information e.g. 4.9.10586.0"
    data_type: "category"
    importance: "medium"
  AvSigVersion:
    description: "Defender state information e.g. 1.217.1014.0"
    data_type: "category"
    importance: "medium"
  IsBeta:
    description: "Defender state information e.g. false"
    data_type: "int8"
    importance: "low"
  RtpStateBitfield:
    description: "NA"
    data_type: "float32"
    importance: "low"
  IsSxsPassiveMode:
    description: "NA"
    data_type: "int8"
    importance: "low"
  DefaultBrowsersIdentifier:
    description: "ID for the machine's default browser"
    data_type: "float32"
    importance: "low"
  AVProductStatesIdentifier:
    description: "ID for the specific configuration of a user's antivirus software"
    data_type: "float32"
    importance: "medium"
  AVProductsInstalled:
    description: "NA"
    data_type: "float32"
    importance: "low"
  AVProductsEnabled:
    description: "NA"
    data_type: "float32"
    importance: "low"
  HasTpm:
    description: "True if machine has TPM"
    data_type: "int8"
    importance: "low"
  CountryIdentifier:
    description: "ID for the country the machine is located in"
    data_type: "int16"
    importance: "medium"
  CityIdentifier:
    description: "ID for the city the machine is located in"
    data_type: "float32"
    importance: "low"
  OrganizationIdentifier:
    description: "ID for the organization the machine belongs in"
    data_type: "float32"
    importance: "low"
  GeoNameIdentifier:
    description: "ID for the geographic region a machine is located in"
    data_type: "float32"
    importance: "low"
  LocaleEnglishNameIdentifier:
    description: "English name of Locale ID of the current user"
    data_type: "int8"
    importance: "low"
  Platform:
    description: "Calculates platform name (of OS related properties and processor property)"
    data_type: "category"
    importance: "medium"
  Processor:
    description: "This is the process architecture of the installed operating system"
    data_type: "category"
    importance: "medium"
  OsVer:
    description: "Version of the current operating system"
    data_type: "category"
    importance: "medium"
  OsBuild:
    description: "Build of the current operating system"
    data_type: "int16"
    importance: "medium"
  OsSuite:
    description: "Product suite mask for the current operating system."
    data_type: "int16"
    importance: "medium"
  OsPlatformSubRelease:
    description: "Returns the OS Platform sub-release (Windows Vista, Windows 7, Windows 8, TH1, TH2)"
    data_type: "category"
    importance: "medium"
  OsBuildLab:
    description: "Build lab that generated the current OS."
    data_type: "category"
    importance: "medium"
  SkuEdition:
    description: "SKU-Edition name useful in population reporting"
    data_type: "category"
    importance: "medium"
  IsProtected:
    description: "Whether a machine is protected"
    data_type: "float32"
    importance: "high"
  AutoSampleOptIn:
    description: "SubmitSamplesConsent value passed in from the service"
    data_type: "int8"
    importance: "low"
  PuaMode:
    description: "Pua Enabled mode from the service"
    data_type: "category"
    importance: "low"
  SMode:
    description: "Field is set to true when the device is known to be in 'S Mode'"
    data_type: "float32"
    importance: "low"
  IeVerIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  SmartScreen:
    description: "SmartScreen enabled string value from registry"
    data_type: "category"
    importance: "medium"
  Firewall:
    description: "True for Windows 8.1 and above if windows firewall is enabled"
    data_type: "float32"
    importance: "medium"
  UacLuaenable:
    description: "Reports whether or not the 'administrator in Admin Approval Mode' user type is disabled or enabled in UAC"
    data_type: "float32"
    importance: "medium"
  Census_MDC2FormFactor:
    description: "A grouping based on a combination of Device Census level hardware characteristics"
    data_type: "category"
    importance: "medium"
  Census_DeviceFamily:
    description: "AKA DeviceClass. Indicates the type of device that an edition of the OS is intended for"
    data_type: "category"
    importance: "medium"
  Census_OEMNameIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_OEMModelIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_ProcessorCoreCount:
    description: "Number of logical cores in the processor"
    data_type: "float32"
    importance: "medium"
  Census_ProcessorManufacturerIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_ProcessorModelIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_ProcessorClass:
    description: "Classification of processors into high/medium/low"
    data_type: "category"
    importance: "low"
  Census_PrimaryDiskTotalCapacity:
    description: "Amount of disk space on primary disk of the machine in MB"
    data_type: "float32"
    importance: "medium"
  Census_PrimaryDiskTypeName:
    description: "Friendly name of Primary Disk Type - HDD or SSD"
    data_type: "category"
    importance: "medium"
  Census_SystemVolumeTotalCapacity:
    description: "Size of the partition that the System volume is installed on in MB"
    data_type: "float32"
    importance: "medium"
  Census_HasOpticalDiskDrive:
    description: "True indicates that the machine has an optical disk drive (CD/DVD)"
    data_type: "int8"
    importance: "low"
  Census_TotalPhysicalRAM:
    description: "Retrieves the physical RAM in MB"
    data_type: "float32"
    importance: "medium"
  Census_ChassisTypeName:
    description: "Retrieves a numeric representation of what type of chassis the machine has."
    data_type: "category"
    importance: "medium"
  Census_InternalPrimaryDiagonalDisplaySizeInInches:
    description: "Retrieves the physical diagonal length in inches of the primary display"
    data_type: "float32"
    importance: "medium"
  Census_InternalPrimaryDisplayResolutionHorizontal:
    description: "Retrieves the number of pixels in the horizontal direction of the internal display."
    data_type: "float32"
    importance: "medium"
  Census_InternalPrimaryDisplayResolutionVertical:
    description: "Retrieves the number of pixels in the vertical direction of the internal display"
    data_type: "float32"
    importance: "medium"
  Census_PowerPlatformRoleName:
    description: "Indicates the OEM preferred power management profile"
    data_type: "category"
    importance: "medium"
  Census_InternalBatteryType:
    description: "NA"
    data_type: "category"
    importance: "low"
  Census_InternalBatteryNumberOfCharges:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_OSVersion:
    description: "Numeric OS version"
    data_type: "category"
    importance: "medium"
  Census_OSArchitecture:
    description: "Architecture on which the OS is based"
    data_type: "category"
    importance: "medium"
  Census_OSBranch:
    description: "Branch of the OS"
    data_type: "category"
    importance: "medium"
  Census_OSBuildNumber:
    description: "OS Build number"
    data_type: "int16"
    importance: "medium"
  Census_OSBuildRevision:
    description: "OS Build revision"
    data_type: "int32"
    importance: "medium"
  Census_OSEdition:
    description: "Edition of the current OS"
    data_type: "category"
    importance: "medium"
  Census_OSSkuName:
    description: "OS edition friendly name"
    data_type: "category"
    importance: "medium"
  Census_OSInstallTypeName:
    description: "Friendly description of what install was used on the machine"
    data_type: "category"
    importance: "medium"
  Census_OSInstallLanguageIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_OSUILocaleIdentifier:
    description: "NA"
    data_type: "int16"
    importance: "low"
  Census_OSWUAutoUpdateOptionsName:
    description: "Friendly name of the WindowsUpdate auto-update settings on the machine."
    data_type: "category"
    importance: "medium"
  Census_IsPortableOperatingSystem:
    description: "Indicates whether OS is booted up and running via Windows-To-Go on a USB stick."
    data_type: "int8"
    importance: "low"
  Census_GenuineStateName:
    description: "Friendly name of OSGenuineStateID"
    data_type: "category"
    importance: "medium"
  Census_ActivationChannel:
    description: "Retail license key or Volume license key for a machine."
    data_type: "category"
    importance: "medium"
  Census_IsFlightingInternal:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_IsFlightsDisabled:
    description: "Indicates if the machine is participating in flighting."
    data_type: "float32"
    importance: "low"
  Census_FlightRing:
    description: "The ring that the device user would like to receive flights for."
    data_type: "category"
    importance: "medium"
  Census_ThresholdOptIn:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_FirmwareManufacturerIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_FirmwareVersionIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_IsSecureBootEnabled:
    description: "Indicates if Secure Boot mode is enabled."
    data_type: "int8"
    importance: "medium"
  Census_IsWIMBootEnabled:
    description: "NA"
    data_type: "float32"
    importance: "low"
  Census_IsVirtualDevice:
    description: "Identifies a Virtual Machine (machine learning model)"
    data_type: "float32"
    importance: "medium"
  Census_IsTouchEnabled:
    description: "Is this a touch device ?"
    data_type: "int8"
    importance: "low"
  Census_IsPenCapable:
    description: "Is the device capable of pen input ?"
    data_type: "int8"
    importance: "low"
  Census_IsAlwaysOnAlwaysConnectedCapable:
    description: "Retrieves information about whether the battery enables the device to be AlwaysOnAlwaysConnected."
    data_type: "float32"
    importance: "low"
  Wdft_IsGamer:
    description: "Indicates whether the device is a gamer device or not based on its hardware combination."
    data_type: "float32"
    importance: "medium"
  Wdft_RegionIdentifier:
    description: "NA"
    data_type: "float32"
    importance: "low"
  HasDetections:
    description: "Target variable, indicates that Malware was detected on the machine"
    data_type: "int8"
    importance: "high"
